# Generated by Django 5.0.1 on 2024-02-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0002_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='sent_date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='received_at',
        ),
        migrations.AddField(
            model_name='message',
            name='sent_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
