# Generated by Django 5.0.1 on 2024-02-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0003_rename_created_at_message_sent_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnseenMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.BigIntegerField()),
                ('receiver', models.BigIntegerField()),
                ('text', models.TextField()),
                ('sent_date', models.DateField()),
                ('sent_time', models.TimeField()),
            ],
        ),
    ]
