# Generated by Django 5.0.1 on 2024-02-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('created_at', models.DateField()),
            ],
        ),
    ]
