# Generated by Django 5.0.1 on 2024-02-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='PASS', max_length=48),
            preserve_default=False,
        ),
    ]
