# Generated by Django 5.0.1 on 2024-02-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0002_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='display',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
